<?php
/**
 * Страница "Форма редактирования учётной записи пользователя".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Editing an account</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/account.png' ?>" />
    </div>
    <p>The form appears after selecting the <b>"Edit account"</b> item from the context menu of the selected user record.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Username.</b> User account name;</li>
        <li><span class="g-help-fld g-help-fld_password"></span> <b>Password.</b> User password;</li>
        <li><span class="g-help-fld g-help-fld_password"></span> <b>Password confirmation.</b> Confirm user password (must match password);</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Status.</b> User account status;</li>
        <li><span class="g-help-fld g-help-fld_listbox"></span> <b>User role.</b>You can select multiple user roles from the list.</li>
    </ul>
</article>