<?php
/**
 * Страница "Форма редактирования учётной записи пользователя".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма редактирования учётной записи</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/account.png' ?>" />
    </div>
    <p>Форма появляется после выбора пункта <b>"Редактировать учётную запись"</b> контекстного меню выбранной записи пользователя.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Имя пользователя.</b> Имя учётной записи пользователя;</li>
        <li><span class="g-help-fld g-help-fld_password"></span> <b>Пароль.</b> Пароль пользователя;</li>
        <li><span class="g-help-fld g-help-fld_password"></span> <b>Подтверждение пароля.</b> Подтверждение пароля пользователя (должен совпадать с поролем);</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Статус.</b> Статус учётной записи пользователя;</li>
        <li><span class="g-help-fld g-help-fld_listbox"></span> <b>Роль пользователя.</b> Из списка можно выбрать несколько ролей пользователей.</li>
    </ul>
</article>