<?php
/**
 * Страница "Форма добавления пользователя".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Add user form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/form.png' ?>" />
    </div>
    <p>The form appears after clicking on the <b>"Add"</b> button on the user list toolbar.</p>
    <h2>Form tabs</h2>
    <h3>Tab "Account"</h3>
    <p>In the tab, fill in the following fields to create a user account:</p>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Username.</b> User account name;</li>
        <li><span class="g-help-fld g-help-fld_password"></span> <b>Password.</b> User password;</li>
        <li><span class="g-help-fld g-help-fld_password"></span> <b>Password confirmation.</b> Confirm user password (must match password);</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Status.</b> User account status;</li>
        <li><span class="g-help-fld g-help-fld_listbox"></span> <b>User role.</b>You can select multiple user roles from the list.</li>
    </ul>

    <h3>Tab "Personal data"</h3>
    <p>In the tab, fill in the following fields to create a user profile:</p>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Call name.</b> A Call name is a name used in messages and letters.;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>First name.</b> User's first name;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Last name.</b> User's last name;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Surname.</b> User's surname;</li>
        <li><span class="g-help-fld g-help-fld_date"></span> <b>Date of birth.</b> User's date of birth;</li>
        <li><span class="g-help-fld g-help-fld_radio"></span> <b>Gender.</b> User gender;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Contact Information / Phone.</b> User contact phone number;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Contact Information / E-mail.</b> User's email.</li>
    </ul>
</article>