<?php
/**
 * Страница "Форма добавления пользователя".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма добавления / редактирования пользователя</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/form.png' ?>" />
    </div>
    <p>Форма появляется после нажатия на кнопку <b>"Добавить"</b> панели инструментов списка пользователей.</p>
    <h2>Закладки формы</h2>
    <h3>Закладка "Учётная запись"</h3>
    <p>В закладке заполняют следующие поля для создания учётной записи пользователя:</p>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Имя пользователя.</b> Имя учётной записи пользователя;</li>
        <li><span class="g-help-fld g-help-fld_password"></span> <b>Пароль.</b> Пароль пользователя;</li>
        <li><span class="g-help-fld g-help-fld_password"></span> <b>Подтверждение пароля.</b> Подтверждение пароля пользователя (должен совпадать с поролем);</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Статус.</b> Статус учётной записи пользователя;</li>
        <li><span class="g-help-fld g-help-fld_listbox"></span> <b>Роль пользователя.</b> Из списка можно выбрать несколько ролей пользователей.</li>
    </ul>

    <h3>Закладка "Личные данные"</h3>
    <p>В закладке заполняют следующие поля для создания профиля пользователя:</p>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Обращение.</b> Обращение - это имя, указываемое в сообщениях и письмах;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Имя.</b> Имя пользователя;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Фамилия.</b> Фамилия пользователя;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Отчество.</b> Отчество пользователя;</li>
        <li><span class="g-help-fld g-help-fld_date"></span> <b>Дата рождения.</b> Дата рождения пользователя;</li>
        <li><span class="g-help-fld g-help-fld_radio"></span> <b>Пол.</b> Пол пользователя;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Контактная информация / Телефон.</b> Контактный телефон пользователя;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Контактная информация / Электронная почта.</b> E-mail пользователя.</li>
    </ul>
</article>