<?php
/**
 * Страница "Список пользователей".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>List of users</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>The list displays all users.</p>
    <h2>List columns</h2>
    <ul class="g-help-list">
        <li><b>User / Last name.</b> User's last name;</li>
        <li><b>User / First name.</b> User's first name;</li>
        <li><b>User / Surname.</b> User's surname;</li>
        <li><b>User / Call name.</b> A call name is a name used in messages and letters.;</li>
        <li><b>Account / Name.</b> User account name;</li>
        <li><b>Account / Roles.</b> User account roles;</li>
        <li><b>Account / Status.</b> User account status;</li>
        <li><b>Account / Side.</b> Side (Site, Control Panel) of user registration;</li>
        <li><b>Authorization / Date.</b> Last date and time of user authorization;</li>
        <li><b>Authorization / Trial.</b> Number of user authorization attempts;</li>
        <li><b>Authorization / Lock date.</b> Date the user account was blocked;</li>
        <li><b>Contacts / Phone.</b> User contact phone number;</li>
        <li><b>Contacts / E-mail.</b> User's email.</li>
    </ul>

    <h2>Toolbar</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-add.svg' ?>" /> <b>Add.</b> Shows the form for adding a user;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-delete.svg' ?>" /> <b>Delete.</b> Delete selected users;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Clear.</b> Deletes all users;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Edit.</b> Shows the form to edit a user;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Select.</b> Selects or deselects users;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Refresh.</b> Refresh the list of users;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Record profiling.</b> Expands or collapses the Navigation Bar to display information about the selected user;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Show / Hide.</b> Shows or hides columns;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Help.</b> Show the help window for the current list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Search.</b> Shows the form for searching records in the list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Filter.</b> Shows the form for filtering records in a list.</li>
    </ul>
</article>