<?php
/**
 * Страница "Список пользователей".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Список пользователей</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>В списке отображаются все пользователи.</p>
    <h2>Столбцы списка</h2>
    <ul class="g-help-list">
        <li><b>Пользователь / Фамилия.</b> Фамилия пользователя;</li>
        <li><b>Пользователь / Имя.</b> Имя пользователя;</li>
        <li><b>Пользователь / Отчество.</b> Отчество пользователя;</li>
        <li><b>Пользователь / Обращение.</b> Обращение - это имя, указываемое в сообщениях и письмах;</li>
        <li><b>Учётная запись / Имя.</b> Имя учётной записи пользователя;</li>
        <li><b>Учётная запись / Роли.</b> Роль пользователя;</li>
        <li><b>Учётная запись / Статус.</b> Статус учётной записи пользователя;</li>
        <li><b>Учётная запись / Сторона.</b> Сторона (Сайт, Панель управления) регистрации пользователя;</li>
        <li><b>Авторизация / Дата.</b> Последняя дата и время авторизации пользователя;</li>
        <li><b>Авторизация / Попыток.</b> Количество попыток авторизации пользователя;</li>
        <li><b>Авторизация / Дата блокировки.</b> Дата блокировки учётной записи пользователя;</li>
        <li><b>Контактная информация / Телефон.</b> Контактный телефон пользователя;</li>
        <li><b>Контактная информация / E-mail.</b> E-mail пользователя.</li>
    </ul>

    <h2>Панель инструментов</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-add.svg' ?>" /> <b>Добавить.</b> Вызывает форму для добавления пользователя;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-delete.svg' ?>" /> <b>Удалить.</b> Удаляет выделенных пользователей;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Очистить.</b> Удаляет всех пользователей;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Правка.</b> Вызвает форму для редактирования пользователя;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Выделить.</b> Выделяет или убирает выделение пользователей;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Обновить.</b> Обновляет список пользователей;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Профилирование записи.</b> Разворачивает или сворачивает Панель навигации для отображения информации о выбранном пользователе;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Скрыть / Показать.</b> Показывает или скрывает столбцы;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Справка.</b> Вызывает окно справочной информации для текущего списка;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Поиск.</b> Вызывает форму поиска записей в списке;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Фильтр.</b> Вызывает форму фильтрации записей в списке.</li>
    </ul>
</article>