<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Пользователи</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Учётные записи пользователей Панели управления и веб-сайта.</p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('grid') ?>">Список пользователей</a></li>
        <li><a href="<?= $url('form') ?>">Форма добавления / редактирования пользователя</a></li>
        <li><a href="<?= $url('account') ?>">Форма редактирования учётной записи пользователя</a></li>
        <li><a href="<?= $url('profile') ?>">Форма редактирования личных данных пользователя</a></li>
    </ul>
</article>