<?php
/**
 * Страница "Форма редактирования личных данных".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма редактирования личных данных</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/profile.png' ?>" />
    </div>
    <p>Форма появляется после выбора пункта <b>"Редактировать личные данные"</b> контекстного меню выбранной записи пользователя.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Обращение.</b> Обращение - это имя, указываемое в сообщениях и письмах;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Имя.</b> Имя пользователя;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Фамилия.</b> Фамилия пользователя;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Отчество.</b> Отчество пользователя;</li>
        <li><span class="g-help-fld g-help-fld_date"></span> <b>Дата рождения.</b> Дата рождения пользователя;</li>
        <li><span class="g-help-fld g-help-fld_radio"></span> <b>Пол.</b> Пол пользователя;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Контактная информация / Телефон.</b> Контактный телефон пользователя;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Контактная информация / Электронная почта.</b> E-mail пользователя.</li>
</article>